 name: Deploy Docusaurus
 on:
   push:
     branches:
     - master
 jobs:
   build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        mkdir -p "$SSH_PATH"
        touch "$SSH_PATH/known_hosts"
        echo "$DEPLOY_SSH_KEY" > "$SSH_PATH/id_rsa"
        chmod 700 "$SSH_PATH"
        chmod 600 "$SSH_PATH/known_hosts"
        chmod 600 "$SSH_PATH/id_rsa"
        eval $(ssh-agent)
        ssh-add "$SSH_PATH/id_rsa"
        ssh-keyscan -t rsa "github.com" >> "$SSH_PATH/known_hosts"
        echo "StrictHostKeyChecking no" >> "$SSH_PATH/config"
        cd $BUILD_DIR
        git config --global user.name "$GIT_USER"
        git config --global user.email "$GIT_EMAIL"  
        npm install
        npm run build
        npx gh-pages -d "build/$PROJECT_NAME" --repo "$GIT_REPO"
      env:
        BUILD_DIR: website
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        PROJECT_NAME: mental_disorder
        GIT_USER: github-action
        GIT_EMAIL: noreply@newmedia.pts.org.tw
        SSH_PATH: '$HOME/.ssh'
        GITHUB_REPOSITORY: 'git@github.com:ptstaiwan/mental_disorder.git'
