 name: Deploy Docusaurus
 on:
   push:
     branches:
     - master
 jobs:
   build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and publish
      run: |
        git config --global user.name "github_actions"
        git config --global user.email "github_actions@noreply.pts.org.tw"
        mkdir -p "/home/runner/.ssh"
        touch "/home/runner/.ssh/known_hosts"
        echo "$DEPLOY_SSH_KEY" > "/home/runner/.ssh/id_rsa"
        chmod 700 "$SSH_PATH"
        chmod 600 "$SSH_PATH/known_hosts"
        chmod 600 "$SSH_PATH/id_rsa"
        eval $(ssh-agent)
        ssh-add "/home/runner/.ssh/id_rsa"
        ssh-keyscan -t rsa "github.com" >> "/home/runner/.ssh/known_hosts"
        echo "StrictHostKeyChecking no" >> "$/home/runner/.ssh/config"
        ssh -Tv git@github.com
        cd $BUILD_DIR
        npm install
        npm run build
        npx gh-pages -d "build/$PROJECT_NAME" --repo "git@github.com:ptstaiwan/mental_disorder.git"
      env:
        BUILD_DIR: website
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        PROJECT_NAME: mental_disorder
